# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbe56d8cc54f94756a65774a5d7d3fd06445c51ae6913499cfd17bda6cee4e94670f8edbdb061aefbef23f62a49ccbebdabef8ac38e753e3418616a6192c0ded

test:
  secret_key_base: 8866a5158549f0c1b97ebc1217af503b9774800a5b34ae1e71e68c74efcad21c442109b556887a95682d65ff2f87562c100412b75a5e64b25a116930f9a4fbf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
